####################################################################################################
# Simulation
ndims = 2
equations = "CompressibleEulerEquations"
gamma = 1.6666666666666667
initial_condition = "initial_condition_blob"
# source_terms =
t_start = 0.0
t_end   = 8.0
# restart = true
# restart_filename = "out/restart_000100.h5"

####################################################################################################
# Solver
solver = "dg"
polydeg = 4
cfl = 0.3
n_steps_max = 15000
analysis_interval = 100
shock_indicator_variable = "pressure"
shock_alpha_max = 0.4
shock_alpha_min = 0.0 # 0.0001
shock_alpha_smooth = true
volume_integral_type = "shock_capturing"
surface_flux = "flux_lax_friedrichs"
volume_flux = "flux_chandrashekar"

####################################################################################################
# Mesh
n_cells_max = 100000
coordinates_min = [-20.0, -20.0]
coordinates_max =  [20.0, 20.0]
initial_refinement_level = 6
# refinement_patches = [
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
#   {type = "box", coordinates_min = [-40.0, -5.0], coordinates_max = [40.0, 5.0]},
# ]
####################################################################################################
# AMR
amr_indicator = "blob"
amr_interval = 0
amr_alpha_max = 1.0 #0.0031
amr_alpha_min = 0.0001
adapt_initial_condition = true

####################################################################################################
# I/O
# save_initial_solution = false
solution_interval = 100
solution_variables = "primitive"
restart_interval = 1000
output_format = "hdf5"
